accelerator: auto
arch: resnet50
batch_size: 128
covariance_coeff: 1.0
data_dir: ./data/image/cifar10
dataset: cifar10
devices: 1
exclude_bn_bias: false
final_lr: 1.0e-06
gaussian_blur: false
input_height: 32
invariance_coeff: 25.0
jitter_strength: 1.0
learning_rate: 0.001
max_epochs: 100
max_steps: -1
mlp: 8192-8192-8192
num_classes: 10
num_nodes: 1
num_samples: 40000
num_workers: 1
online_ft: false
optimizer: adam
start_lr: 0
variance_coeff: 25.0
warmup_epochs: 10
weight_decay: 1.0e-06
